### ISSUE TITLE
헤더쪽 라우터 설정

### ISSUE THREAD

**Issue by vomvoru** [snack-news/Snack-FE#128]
![image](https://user-images.githubusercontent.com/6327830/63224468-b3455f00-c1ff-11e9-875a-f1cd6ee70c76.png)

![image](https://user-images.githubusercontent.com/6327830/63224471-ba6c6d00-c1ff-11e9-9bab-ca39d9d0c738.png)

위와 같은 헤더의 뒤로가기, 로고 클릭시 링크 이동

**Comment by MartinYounghoonKim** [comment]
완료되었습니다.
