### ISSUE TITLE
open graph meta data 추가

### ISSUE THREAD

**Issue by vomvoru** [snack-news/Snack-FE#180]

**Comment by seanlion** [comment]
타이틀, 이미지, 디스크립션 등 필요한 항목을 승님에게 주세용

**Comment by seanlion** [comment]
메타 데이터 추가했습니다.
https://docs.google.com/spreadsheets/d/1nuTBau4rnT9SN3Q7mknsirYsqseokpsx_8hGFYJyoxE/edit#gid=1723605906

**Comment by MartinYounghoonKim** [comment]
#254
