### ISSUE TITLE
IntroduceFormPage 여백 오류

### ISSUE THREAD

**Issue by vomvoru** [snack-news/Snack-FE#21]
![image](https://user-images.githubusercontent.com/6327830/60482939-64cf1600-9cce-11e9-9a88-54ba19c60848.png)

'Snack에 소개하고 싶은 소식이나 링크를 알려주세요!' 문장 아래에 여백 제거가 필요할것 같습니다

**Comment by MartinYounghoonKim** [comment]
@vomvoru 
#24  에서 수정되었습니다.
