### ISSUE TITLE
config로 변경

### ISSUE THREAD

**Issue by MartinYounghoonKim** [snack-news/Snack-FE#23]
src/constants.ts 오히려 이 파일에서의 역할은 상수보다는 config에 가까운 것 같습니다.

**Comment by vomvoru** [comment]
#27 에서 작업 하였습니다.

**Comment by vomvoru** [comment]
저렇게 댓글 계속 적는거 귀찬은데 .. 뭔가 방법이 없을까요..ㅠㅠㅋㅋ
