### ISSUE TITLE
svg 사용에 대한 논의

### ISSUE THREAD

**Issue by vomvoru** [snack-news/Snack-FE#33]
일부 이미지(아이콘)이 흐리게 나옵니다.
svg 를 사용해야할것같은데 이슈가 있을수 있어서 논의용 issue 만들었습니다.
논의 결과에 따라 svg 를 사용하거나 x3 이미지 사용을 해야할것 같습니다 (현재는 x2 이미지 사용중입니다)

**Comment by seanlion** [comment]
아이콘과 로고같은건 여기 참고하세요.
https://zpl.io/aMplENm

**Comment by vomvoru** [comment]
3x 사용하니까 깔끔하게 보이네용
