### ISSUE TITLE
회사 선택 리스트 페이지

### ISSUE THREAD

**Issue by vomvoru** [snack-news/Snack-FE#35]
![image](https://user-images.githubusercontent.com/6327830/60750850-614ad000-9fe9-11e9-8d0c-bc1dd8ebd539.png)

1."전체" 텍스트 있는 영역이 width깨짐. 피씨에서 모웹환경(width : 756px)으로 본건데, 깨짐.
공통적용 : 이 영역도 아이콘이 흐린 것 같음.

**Comment by seanlion** [comment]
이거는 수정된 제플린 꼭 참조 바람.
https://zpl.io/2ZrvgME

[수정사항]
1.아이콘 색 변경(화살표), 아이콘 변경(가나다순 아이콘)
2.회사 로고 백그라운드 컬러 지정함.

**Comment by seanlion** [comment]
확인완료
