### ISSUE TITLE
주차 선택

### ISSUE THREAD

**Issue by vomvoru** [snack-news/Snack-FE#40]
![image](https://user-images.githubusercontent.com/6327830/60751694-64e45400-9ff5-11e9-853d-1e506f55997f.png)

1.실 화면으로 보니 "체크"아이콘이랑 "닫기"아이콘이랑 간격이 차이가 나는듯. 체크 아이콘을 왼쪽으로 4px정도 이동 가능할까요
-> 여백빼고 아이콘 제공 예정

#42 작업 이후에 진행 필요

**Comment by seanlion** [comment]
https://zpl.io/29OZn8A
제플린에 수정완료
제플린 보시면, 터치영역은 잡아놓았고,대신 아이콘은 여백없이 올려놓았습니다.

**Comment by seanlion** [comment]
확인완료
