### ISSUE TITLE
더보기 버튼 디자인 다시하기

### ISSUE THREAD

**Issue by vomvoru** [snack-news/Snack-FE#41]
![image](https://user-images.githubusercontent.com/6327830/60751723-cc9a9f00-9ff5-11e9-8e7e-c0aac77ae3dd.png)

"더보기 버튼" -> 본문 텍스트 오른쪽에 위치할 순 없나요?( 이건 버튼 디자인 다시 하기)

**관련 이슈**
- #31

**Comment by seanlion** [comment]
https://zpl.io/2p41YQ8
제플린에 수정완료
버튼 윗 아래 간격 주의해주세용!

**Comment by seanlion** [comment]
확인완료
