### ISSUE TITLE
공유하기 아이콘 컬러 변경

### ISSUE THREAD

**Issue by vomvoru** [snack-news/Snack-FE#43]
![image](https://user-images.githubusercontent.com/6327830/60751833-89413000-9ff7-11e9-9393-62e7abec04be.png)

아이콘도 "공유하기" 컬러랑 똑같이 적용할 수 있을까요(#595966) (아이콘 2개 다 공통) -> svg 여부 조사부터 해보고, 안되면 색깔을 바꿔서 아이콘을 다시 드림.(3x버전)

**Comment by vomvoru** [comment]
#33 참고 (svg 논의)

**Comment by seanlion** [comment]
확인완료
