### ISSUE TITLE
외부 링크 전달

### ISSUE THREAD

**Issue by vomvoru** [snack-news/Snack-FE#44]
![image](https://user-images.githubusercontent.com/6327830/60751896-b80bd600-9ff8-11e9-9097-8274fca1ff7f.png)

각각의 링크 전달

**Comment by seanlion** [comment]
[a태그 링크 모음]
서비스 안내 버튼 : '서비스 안내 페이지'
제안하기 버튼 : "제안하기 페이지"
문의하기 버튼 : "문의하기 페이지"
페이스북 그룹 : https://www.facebook.com/groups/snacknews/
카카오톡 그룹 : https://open.kakao.com/o/gKIXUx0
트위터 : https://twitter.com/techsnacknews
메일 : teamsnackofficial@gmail.com
