### ISSUE TITLE
1월 2주 옆 아래 화살표 이미지 변경

### ISSUE THREAD

**Issue by vomvoru** [snack-news/Snack-FE#45]
![image](https://user-images.githubusercontent.com/6327830/60751944-5ac45480-9ff9-11e9-96f5-c94e4f548018.png)

"1월2주" 텍스트 옆의 화살표 아이콘은 # 121111로 칼라값 변경해야 할듯.
-> svg로 이미지 변경후 색 변경하거나, 색이 다른 이미지를 승님께서 제공할 예정

**Comment by seanlion** [comment]
https://zpl.io/2p41YQ8
아이콘은 아이콘 페이지에서 확인해주세용.
