### ISSUE TITLE
문의 페이지(IntroduceFormPage)

### ISSUE THREAD

**Issue by vomvoru** [snack-news/Snack-FE#46]
![image](https://user-images.githubusercontent.com/6327830/60751969-e0e09b00-9ff9-11e9-9d15-72371ebf6a3e.png)

1.제출하기 버튼이랑 밑에 있는 footer 간격을 더 줄여도 좋을듯. 간격을 "55px"로 변경하면 한 화면에 다 들어오는듯.

**Comment by seanlion** [comment]
제플린에서 확인해주세용.
https://zpl.io/adXRqr5
