### ISSUE TITLE
메뉴 리스트 (MenuPage)

### ISSUE THREAD

**Issue by vomvoru** [snack-news/Snack-FE#47]
![image](https://user-images.githubusercontent.com/6327830/60751989-2ef59e80-9ffa-11e9-9cb2-fff103d750c6.png)

1. 닫기 아이콘이랑 "menu" 텍스트 간격을 35px로 변경하면 모바일에서 모든 내용이 한 화면에 다 들어오는 것 같음.
2. "menu"텍스트랑 메뉴명 텍스트들, 닫기 아이콘이 왼쪽 간격이 좀 좁아보임. left 간격이 40px로 가면 좋을 것 같음.

**Comment by seanlion** [comment]
모든 수치는 제플린에 있는거로 적용 부탁드립니다.
https://zpl.io/VDAE8Xv

**Comment by vomvoru** [comment]
이미지 배경이 투명이 아니라서 승님께 해당사항 전달하였습니다.

**Comment by seanlion** [comment]
확인완료
