### ISSUE TITLE
Picks 페이지(PicksPage)

### ISSUE THREAD

**Issue by vomvoru** [snack-news/Snack-FE#48]
![image](https://user-images.githubusercontent.com/6327830/60752001-711ee000-9ffa-11e9-9496-306b1cf4da58.png)

1. picks 탭에 파란선이 있어야 함.
2. 그 밑에 카테고리 부분(개발,비즈니스 등)에 파란색 컬러 부분 먹은 케이스도 필요.

**작업 생략 (메모용)**
1. news/picks 탭 부분의 width가 다른 부분과 다름. 조정 필요. (#30 의 max width 설정으로 조정될 예정)
2. 그리고 생각보다 개발 읽기 텍스트 영역 부분이랑 아티클 사이에 있는 회색부분 & 아티클 사이사이에 있는 회색 부분 간격이 너무 좁아보임. 이 부분을 40px까지 늘려볼까 아니면 40px까지 늘리고 색을 흰색쪽으로 바꿔볼까? -> 이건 좀더 생각해보는 걸로.

**Comment by seanlion** [comment]
https://zpl.io/VKPq648
1번과 2번은 적용해주시면 될 것 같고,그 picks탭에 파란선말고 그 옆부분 선은 1px로 수정해놓았습니다.

그리고 6번 코멘트 한번 봐주시고. 5번 코멘트 부분에 안내 텍스트도 변경햇으니 참고 부탁드립니다.

**Comment by seanlion** [comment]
확인완료 했는데 제플린의 6번 코멘트는 처리 x
