### ISSUE TITLE
회사로고 베리에이션 UI에 반영

### ISSUE THREAD

**Issue by seanlion** [snack-news/Snack-FE#62]
![image](https://user-images.githubusercontent.com/26603454/61130881-b0fe2f80-a4f2-11e9-978f-f4325f74059e.png)
회사로고 우버 말고 다른 것도 UI에 반영해서 테스트해보기(#35 연결)

**Comment by MartinYounghoonKim** [comment]
쿠팡 로고 추가되었습니다. 해당 이슈 종료하도록 하겠습니다.
