### ISSUE TITLE
#63 작업 진행에 따른 사이드 이펙트 에러 처리

### ISSUE THREAD

**Issue by vomvoru** [snack-news/Snack-FE#75]
#63 에서 이미지 x3으로 변경하였는데 일부분에서 사이드 이펙트로
이미지가 너무 크게 보이거나 안보이는 이슈가 있어서
버그 제거작업 진행할ㄲㅔ요

**Comment by seanlion** [comment]
이건 대략 어느정도 걸릴지 알려주세용
