### ISSUE TITLE
FE 빌드 & 실행 스크립트 요청드립니다. 

### ISSUE THREAD

**Issue by NESOY** [snack-news/Snack-FE#84]
서버 배포하기 위한 필요한 정보 🙏
- 테스트 스크립트
- 빌드 스크립트
- 실행 스크립트
- 포트 번호

**Comment by vomvoru** [comment]
늦어서 죄송합니다.

# 초기 실행 필요 스크립트
npm install

# 테스트 스크립트
아직 준비되지 않았습니다.
(2개 프로세스(storybook, jest)를 실행해야 되는데 아직 2개를 적절한 순서(타이밍)으로 실행하는 스크립트가 만들어지지 않았습니다.  개발시에는 storybook을 실행후 실행 완료시 jest 로 테스트를 진행합니다.)

# 빌드 스크립트
npm run build

#서버 실행 스크립트
npm run server

# 포트 번호
3000

**Comment by NESOY** [comment]
감사합니다 :)

**Comment by MartinYounghoonKim** [comment]
해당 이슈 종료하겠습니다. :)
