### ISSUE TITLE
Full Width로 된 것 수정

### ISSUE THREAD

**Issue by seanlion** [snack-news/Snack-FE#99]
4.메뉴가 pc로 보면 full width로 보인다.
홈 page랑 똑같은 width로 맞춰야 될듯.
https://snack-news-storybook.netlify.com/iframe.html?id=pages-menupage--default

5.pick page 너비가 이상하다.
https://snack-news-storybook.netlify.com/iframe.html?id=pages-pickspage--default
이것도 news page랑 똑같은 width로 맞춰야 될듯.
그리고 처음 들어왔을때 default 옵션이 picks탭에 focus되야하는데 news탭에 되어있습니당.

**Comment by vomvoru** [comment]
Pick 페이지는 추후 진행할께요!
